services:
  - type: web
    name: tgm2
    env: node
    buildCommand: chmod +x ./build.sh && ./build.sh
    startCommand: cd backend && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        sync: false
    runtime: mixed
    buildFilter:
      paths:
        - backend/**
        - package.json
        - build.sh
        - requirements.txt
